<h1>COURTSHIP: ROMANCE WITH A PURPOSE</h1>
    						<p>Courtship: Romance with a Purpose
Most people will always have something to share when courtship is tackled. It may come as old-fashioned to others or so modern-day to some.  Since the beginning, there had been lots of courtship definitions and now, it simply depends on how the person perceives it. Generally, it is the act of wooing in love to the opposite sex in the process that includes dating, meeting online, chatting on line, sending letters, exchanging text messages, talking over the phone, sending flowers, gifts, love songs, love quotes, and so much more as long as love is expressed.</p> 
<p>In the real sense, it must be more than that. It is more than the long walks under the moonlight, extended talks over the phone, or even the sweet exchange of messages. It is simply more than the getting to know stage. </p>
Courtship is a season of romance with a purpose. A usual love story would simply blossom in friendship and take a step into courtship which is a new season of friendship. Yes, we defined courtship as wooing but it must have a purpose. And this stage of courtship must be the time wherein the two individuals would take time to deepen their relationship and explore the possibility of marriage.
It may sound somehow strange to you but this is actually the real value of courtship. You would never wish to end up with the wrong person, right? So, as you enter the courtship phase, it must be something that you must have thought about. This is to avoid the moment of pain and tears of being heart broken. 
For the men, this principle of courtship is something that we must bring on as we pursue that special someone. For women, evaluate yourselves first before you engage yourselves in that season.
And as you have this purposeful romance of courtship, savor every moment of it because it will be something different between the two of you. This would be something worth cherishing and reminiscing which will bring rainbows and smiles in your love stories.
Have that purposeful romance as you discover each other in the season of courtship! </p>
